name: CI

on: 
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: use node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci #install dependencies
      - run: npm format:check # check code formatting
      - run: npm test -- --coverage # run test 
        env:
          CI: true # this will remove any use prompts in running the tests